name: "GitGuardian Shield Action"
description: "Scan commits for secrets and other issues."
author: GitGuardian <support@gitguardian.com>

inputs:
  args:
    description: |
      Arguments to pass to `ggshield secret scan ci`.

      [`ggshield secret scan ci` reference](https://docs.gitguardian.com/ggshield-docs/reference/secret/scan/ci).
    required: false
branding:
  icon: "shield"
  color: "blue"
runs:
  using: "docker"
  image: "docker://gitguardian/ggshield:v1.28.0"
  entrypoint: "/bin/bash"
  args:
    - -c
    - ggshield secret scan --recursive ${{ inputs.args }} path .
