name: Application Release

on:
  push:
    tags:
      # Trigger workflow on push events for version tags (e.g. v1.28.0) but not for major version tag (e.g. v1)
      - "v*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## Changelog
          draft: false
          prerelease: false
